version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8088:80" # Map container port 80 to host port 8000
    volumes:
      - .:/var/www/html # Sync files between host and container for local development
    environment:
      # Application Settings
      - APP_NAME=OBDCAll
      - APP_ENV=local
      - APP_KEY=base64:qE4/MPXAIjz3a4X6tjixA/oKmXe8UoRbDYS4FFyjEmU=
      - APP_DEBUG=true
      - APP_URL=http://192.168.29.58:8088

      # Logging Settings
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug

      # Database Settings
      - DB_CONNECTION=mysql
      - DB_HOST=db # Link to the MySQL container service if using MySQL in Docker Compose
      - DB_PORT=3306
      - DB_DATABASE=tdp_call
        #- DB_USERNAME=tdp_portal
        #- DB_PASSWORD=TDP-YJ_Po5tm@n

      # Cache and Session Settings
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=10080

      # Redis Settings
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      # Mail Settings
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=suhasiniravichandran123@gmail.com
      - MAIL_PASSWORD=oxmakvbovqbdqefh
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=suhasiniravichandran123@gmail.com

      # AWS Settings
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: DB-apk@YJ_626101
      MYSQL_DATABASE: tdp_call
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password@123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:

