image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DB_HOST: 192.168.29.58
  DB_PORT: 3306
  DB_DATABASE: tdp_call
  DB_USERNAME: admin
  DB_PASSWORD: Password@123

before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

stages:
  - build
  - deploy
  - rollback
  - clean_up

build:
  stage: build
  tags:
    - docker
  script:
    - set -e  # Exit if any command fails
    - docker info
    - docker build -t $DOCKER_USERNAME/my-laravel-app .
    - docker tag $DOCKER_USERNAME/my-laravel-app $DOCKER_USERNAME/my-laravel-app:latest
    - docker push $DOCKER_USERNAME/my-laravel-app:latest
  after_script:
    - |
      if [ $? -ne 0 ]; then
        echo "Build failed, triggering rollback..."
        exit 1
      fi

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - set -e  # Exit if any command fails
    - docker network create my-network || true

    # Backup existing containers
    - docker commit my-laravel-app my-laravel-app-backup || true
    - docker commit 192.168.29.58 my-laravel-db-backup || true

    # Stop and remove old containers
    - docker ps -q --filter "name=192.168.29.58" | xargs -r docker stop | xargs -r docker rm
    - docker ps -q --filter "name=my-laravel-app" | xargs -r docker stop | xargs -r docker rm

    # Remove old volumes
    - docker volume ls -q --filter "name=laravel_data" | xargs -r docker volume rm
    - docker volume ls -q --filter "name=mysql_data" | xargs -r docker volume rm

    # Deploy new containers
    - docker run -d --name 192.168.29.58 --network my-network -e MYSQL_ROOT_PASSWORD=$DB_PASSWORD -e MYSQL_DATABASE=$DB_DATABASE -p 3307:3306 -v mysql_data:/var/lib/mysql mysql:8
    - docker run -d --name my-laravel-app --network my-network -p 8088:80 -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -e DB_DATABASE=$DB_DATABASE -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD -v laravel_data:/var/www/html $DOCKER_USERNAME/my-laravel-app:latest
  after_script:
    - |
      if [ $? -ne 0 ]; then
        echo "Deploy failed, triggering rollback..."
        exit 1
      fi

rollback:
  stage: rollback
  tags:
    - docker
  script:
    - echo "Rolling back to previous working version..."
    - docker stop my-laravel-app || true
    - docker rm my-laravel-app || true
    - docker run -d --name my-laravel-app --network my-network -p 8088:80 my-laravel-app-backup
    - docker stop 192.168.29.58 || true
    - docker rm 192.168.29.58 || true
    - docker run -d --name 192.168.29.58 --network my-network -p 3307:3306 mysql:8
  when: on_failure
  allow_failure: false

clean_up_job:
  stage: clean_up
  tags:
    - docker
  script:
    - docker system prune -af
  when: always


