# Use an official Nginx image as the base
FROM nginx:latest

# Copy the static HTML file to the Nginx directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to allow access to the web server
EXPOSE 80

